### ISSUE TITLE
Incorrectly typed exception

### ISSUE THREAD

**Issue by foxyblue** [checkout/checkout-sdk-python#135]
The `CheckoutApiException` has incorrectly defined types

### Description

The [CheckoutApiException](https://github.com/checkout/checkout-sdk-python/blob/main/checkout_sdk/exception.py#L32) is defined as having `error_details` as a `dict` when we can see in the `__init__` method that `self.error_details` can be set to `None`. Thus `error_details` is actually `Optional[dict]`.

However, in some cases `error_details` may not be set when `response.text` is `null` or missing. An example of such case is when the API responds with a `403` on a payout, `error_details` is not an available attribute on this exception. Which also means the python examples in the documentation isn't complete for this case and raises an AttributeError on 403.

<div  align="center">
<img width="366" alt="image" src="https://github.com/checkout/checkout-sdk-python/assets/28621737/d27937da-6bd0-4014-a5c7-8da88647bab2">
</div>

Lastly `error_details` should actually be a `list` instead of a `dict` according to the API documentation, as you can see in the image provided [the API mentions](https://api-reference.checkout.com/#operation/requestAPaymentOrPayout!c=422&path=error_codes&t=response) that `error_codes` is an array
<div  align="center">
<img width="407" alt="image" src="https://github.com/checkout/checkout-sdk-python/assets/28621737/7cf89bd4-19e0-4952-8d29-7c421b04c2f3">
</div>

### Additional information

A final point, it would be worthwhile introducing some clear data structures to this library as most of the structs have to be guessed by reading the [attributes in the tests](https://github.com/checkout/checkout-sdk-python/blob/main/tests/payments/get_payment_details_integration_test.py#L15-L30). This would be far more helpful than trying to figure out the struct from a nested ResponseWrapper object.

**Comment by armando-rodriguez-cko** [comment]
Thank you very much @foxyblue for your comments.
We will revise and make any necessary changes in future releases as far as possible.

**Comment by armando-rodriguez-cko** [comment]
New release pending
