### ISSUE TITLE
Documentation around making a payment is incorrect

### ISSUE THREAD

**Issue by ironslob** [checkout/checkout-sdk-python#17]
The documentation in the `README.md` has some useful, specific examples about how to request a payment. However, having tried to request a payment using the `Source Type: token` example it appears that the documentation does not match the code.

The example given is:

```
    payment = api.payments.request(
        source={
            'token': 'tok_...'.
            'billing_address': { ... },
            'phone': { ... }
        },
        amount=100,                                     # cents
        currency=sdk.Currency.USD,                      # or 'usd'
        reference='pay_ref'
    )
    print(payment.id)
```

However, this gives a `ValueError` because the underlying code cannot determine the request type - `ValueError: Payment source missing. Please specify a valid card or token.`.

Having looked through the code I determined that the `token` field should be a top level item, alongside `source`. This fixed the immediate problem, but then raised another in that validation was expecting a `customer` attribute as well, which contained either the email address, or customer ID. This is also undocumented.

**Comment by ironslob** [comment]
It seems that the latest README references a beta version of 2.0, and not the stable version currently out in the world. Updated to latest beta and documentation matches expectation.

**Comment by moyuanhuang** [comment]
Hi, having a similar question of this issue - From the [API doc](https://api-reference.checkout.com/#operation/requestAPaymentOrPayout) it looks like the client need to provide a payment source token when requesting payments.

However, from some types of payments, for example iDeal, the starter doc indicates [different sample request](https://www.checkout.com/docs/payments/payment-methods/bank-transfers/ideal#Request_example).

Wonder which one is the source of truth?
