### ISSUE TITLE
Inconsistent error handling

### ISSUE THREAD

**Issue by lukzmu** [checkout/checkout-sdk-python#2]
When giving bad card data on purpose while doing a payment request, the exception from `CheckoutSdkError` is missing values forcing me to run the exception handling this way:

```python
except checkout.errors.CheckoutSdkError as e:
        status_code = e.http_status if e.http_status is not None else 500
        abort(status_code, e.message, error_code=e.error_code)
```

**Comment by nicolas-maalouf-cko** [comment]
Hi @lukzmu can you please provide a sample implementation that would allow us to reproduce this behaviour?

Thanks

**Comment by lukzmu** [comment]
```python
import checkout_sdk as sdk

try:
    api = sdk.get_api()
    payment = api.payments.request(
        card={
            'number': '4242424242424242',
            'expiryMonth': 6,
            'expiry_year': 2000,  # bad year
            'cvv': '100'
        },
        value=100,
        currency='gbp',
        customer='test@test.com'
    )
    return payment.http_response.body
except sdk.errors.CheckoutSdkError as e:
    print(e.http_status)  # No such thing as e.http_status


```

**Comment by riaz-bordie-cko** [comment]
Hello @lukzmu, thanks for reaching out.

The behaviour is the expected one. However, I've given it some thought and contemplating something that will make your integration simpler/cleaner.

Please give me a few days, as I need to consider existing integrations, and I'll get something pushed out.

**Comment by riaz-bordie-cko** [comment]
Hello @lukzmu, sorry for the late reply.

Please see this branch: https://github.com/checkout/checkout-sdk-python/tree/feat/better-exception-handling

- All business validations will now be handled at API level, hence `http_status` is always populated
- Incorrect usage would raise `ValueError` and `TypeError`

It's a much simpler approach. 

I will push this out to *master* soon.

**Comment by lukzmu** [comment]
This is great, thank you!
