### ISSUE TITLE
[QUESTION] Why classes have no __init__ methods?

### ISSUE THREAD

**Issue by michaeljaszczuk** [checkout/checkout-sdk-python#37]
Hi,

I just started implementing updated SDK version and i wonder why none of requests related classes (for example: PaymentRequest, RefundRequest) or related objects (for example: CustomerRequest, ThreeDsRequest) has no __init__ methods? Is it conceptional or you don't mind if i add it?

Btw who i should contact to contribute? :) 

Regards,
Michael

**Comment by rsaestrela** [comment]
Hi @michaeljaszczuk. Thanks for creating this issue. All the classes have the default/implicit default constructor. What kind of `init` methods are you looking for? Parameterized `init` methods with all the class attributes and their initialization?

**Comment by michaeljaszczuk** [comment]
Exactly, 

For example implementation of:

``` payment_request = PaymentRequest()
            payment_request.amount = 123
            payment_request.payment_type = PaymentType.REGULAR
            payment_request.capture = auto_capture
           
            source = RequestSource(type_p=PaymentSourceType.ID)
            source.card = card_id
            payment_request.source = source

            three_ds = ThreeDsRequest()
            three_ds.enabled = True
            payment_request.three_ds = three_ds


            # Metadata (Tags):
            if adhoc_tag:
                payment_request.metadata = {'udf1': tag}
```

Could be done in that way:
```
           payment_request = PaymentRequest(
                amount=123,
                payment_type=PaymentType.REGULAR,
                capture=True,
                source=RequestSource(type_p=PaymentSourceType.ID, card_id=card_id)
                three_ds=ThreeDsRequest(
                    enabled=True
                )
            )
```

Also i believe very useful would be add PaymentStatus Enum to common/enums.py 

If you don't mind i could create PR for that but i believe i have no access to do it

**Comment by rsaestrela** [comment]
Ok. I've just noticed in your code snippets `RequestSource(type_p=PaymentSourceType.ID)`. This can be replaced with `RequestIdSource()`. There are different implementations for `RequestSource` (which is not meant to be used directly):

* RequestCardSource
* RequestCustomerSource
* RequestDLocalSource
* RequestIdSource
* RequestNetworkTokenSource
* RequestTokenSource

You can find the code source for them in these 2 files (depending on your keys):
* [Payments (Default)](https://github.com/checkout/checkout-sdk-python/blob/main/checkout_sdk/payments/payments.py)
* [Payments (Four)](https://github.com/checkout/checkout-sdk-python/blob/main/checkout_sdk/payments/payment_apm_four.py)

Same with `RequestDestination` for Payouts, or any other class in this SDK that has declared inheritance.

Going back to the original question, the reason why we decided not to implement `init` methods for each class is **maintainability**. Some classes have a bigger number of attributes, there are hundreds on classes and we want to keep the codebase clean and easier to maintain as possible. I see the utility of these constructors in certain situations but we cannot affort to add them and maintain all that code or simply to add some of them which will create inconsistencies in the code (some classes have them, others don't, why?). Some programming languages have this [feature ootb](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer), others have libraries that [generate this code automatically](https://projectlombok.org/features/constructor). Unfortunately we don't know any similar solution for Python. Anything you can recommend? 

This is not a hard no... We'd be happy you can help us with it but if you do it please try to implement that solution consistently across all project classes, or just a module to start (payments for example). Just a reminder that we're building v3 beta and if we really want to make these commitment then we will have to keep them :)

**Comment by michaeljaszczuk** [comment]
Right, understand 🤔 Thanks for clarification, in that case we can close the ticket :)
