### ISSUE TITLE
Request: custom response classes

### ISSUE THREAD

**Issue by aqeelat** [checkout/checkout-sdk-python#67]
ResponseWrapper does not provide contextual hints on what fields it has.

<img width="872" alt="Screen Shot 2022-06-08 at 3 00 47 PM" src="https://user-images.githubusercontent.com/5212744/172611195-aaa13f5c-9f84-4736-b700-8eb8d5cb22c4.png">

I suggest creating custom response classes for each `checkout_sdk.client.Client` subclass, or even for each operation.

**Comment by Armando-Ibarra** [comment]
Hi @aqeelat 
We did not receive enough feedback to apply custom object wrapper for responses.
I'm going to close this request as won't do for now, but if you need help, please feel free to open or reopen as needed.

Thanks!
