### ISSUE TITLE
How to get All reports

### ISSUE THREAD

**Issue by JonhSilver** [checkout/checkout-sdk-python#70]
How to get?

1. All payments ALL details
2. All Payouts (Transfers) ALL Details
3. All Disputes ALL details
4. Each Payments all fees
5. All Refunds ALL details

**Comment by Armando-Ibarra** [comment]
Hi @JonhSilver 
Depending of you needs, you can check it out the API reference
Default: https://api-reference.checkout.com/
Four: https://api-reference.checkout.com/preview/crusoe/

If you have specific questions about the usage please let us know

**Comment by JonhSilver** [comment]
Yea i can, but there are no any useful info

**Comment by Armando-Ibarra** [comment]
@JonhSilver is there anything else we can help? otherwise I'll close this issue.
